<a href="https://colab.research.google.com/github/Rogerio-mack/fNIRS/blob/main/A_Carol_Positions2D3D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Mount Google Drive

In [2]:
#@markdown
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Common Imports

In [3]:
#@markdown 
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

import h5py
from itertools import compress
from sklearn.preprocessing import scale
from google.colab import widgets

# Routines

In [4]:
#@markdown `def clone_snirf(path_in, path_out, fname='out.snirf')`
def clone_snirf(path_in, path_out, fname='out.snirf'):
  
  if path_in == path_out:
    print('Error: path_in and path_out can not be the same.') 
    return

  if not os.path.exists(path_out):
      os.mkdir(path_out)
      print("Directory " , path_out ,  "was created")
  else:    
      print("Warning: directory " , path_out ,  " already exists")

  if os.path.exists(path_out + fname):
    os.remove(path_out + fname)
    print('Warning: previous output file was deleted.')
  
  print('Input snirf file: ' + path_in + fname)

  fs = h5py.File(path_in + fname,'r')
  fd = h5py.File(path_out + fname,'w')

  if list(fs.keys()).count('formatVersion') >= 1:
    fs.copy('formatVersion',fd,'formatVersion') 
  else:
    print('Warning: there is no formatVersion key in snirf input.')

  if list(fs.keys()).count('nirs') >= 1:
    fs.copy('nirs',fd,'nirs') 
  else:
    print('Error: Invalid snirf file. There is no nirs key in snirf input.')  
  
  print('Output snirf file: ' + path_out + fname)
  
  fd.close()
  fs.close()

  return

# Dados da Fernanda

In [7]:
import os
path_in = '/content/drive/MyDrive/coletas IC TCC/dadosaqui/'
path_out= '/content/snirf/'

print('\n\n Alguns files no diretório... \n\n')
print( os.listdir(path_in + 'snirf/')[0:5] )

fname = 'JMVR_TCC_50.snirf'
clone_snirf(path_in + 'snirf/', path_out, fname=fname)
data = h5py.File(path_out + fname,'r+')

print('\n\n ' + fname + ' sourcePos2D e sourcePos3D... \n\n')
print( data['nirs']['probe']['sourcePos2D'][:] )
print()
print( data['nirs']['probe']['sourcePos3D'][:] )
print()

fname = 'JMVR_TCC_14.snirf'
clone_snirf(path_in + 'snirf/', path_out, fname=fname)
data = h5py.File(path_out + fname,'r+')

print('\n\n ' + fname + ' sourcePos2D e sourcePos3D... \n\n')
print( data['nirs']['probe']['sourcePos2D'][:] )
print()
print( data['nirs']['probe']['sourcePos3D'][:] )
print()




 Alguns files no diretório... 


['JMVR_TCC_50.snirf', 'JMVR_TCC_41.snirf', 'JMVR_TCC_14.snirf', 'JMVR_TCC_28.snirf', 'JMVR_TCC_44.snirf']
Input snirf file: /content/drive/MyDrive/coletas IC TCC/dadosaqui/snirf/JMVR_TCC_50.snirf
Output snirf file: /content/snirf/JMVR_TCC_50.snirf


 JMVR_TCC_50.snirf sourcePos2D e sourcePos3D... 


[[-0.71483462 -0.27727633]
 [-0.35501285  0.20489667]
 [ 0.74574185 -0.30838679]
 [ 0.37013878  0.21963974]]

[[-0.71483462 -0.27727633  0.06287737]
 [-0.35501285  0.20489667  0.1159869 ]
 [ 0.74574185 -0.30838679  0.09993959]
 [ 0.37013878  0.21963974  0.08378406]]

Input snirf file: /content/drive/MyDrive/coletas IC TCC/dadosaqui/snirf/JMVR_TCC_14.snirf
Output snirf file: /content/snirf/JMVR_TCC_14.snirf


 JMVR_TCC_14.snirf sourcePos2D e sourcePos3D... 


[[-0.73120815 -0.27216029]
 [-0.30366807  0.21175215]
 [ 0.72204567 -0.30613718]
 [ 0.32516399  0.19784874]]

[[-0.73120815 -0.27216029  0.07292681]
 [-0.30366807  0.21175215  0.12993451]
 [ 0.72204567

# Dados da Carol

In [8]:
import os
path_in = '/content/drive/MyDrive/Cond 2/'
path_out= '/content/snirf/'

print('\n\n Alguns files no diretório... \n\n')
print( os.listdir(path_in + 'snirf/')[0:5] )

fname = '26_run2.snirf'
clone_snirf(path_in + 'snirf/', path_out, fname=fname)
data = h5py.File(path_out + fname,'r+')

print('\n\n ' + fname + ' sourcePos2D e sourcePos3D... \n\n')
print( data['nirs']['probe']['sourcePos2D'][:] )
print()
print( data['nirs']['probe']['sourcePos3D'][:] )
print()

fname = '19_run2.snirf'
clone_snirf(path_in + 'snirf/', path_out, fname=fname)
data = h5py.File(path_out + fname,'r+')

print('\n\n ' + fname + ' sourcePos2D e sourcePos3D... \n\n')
print( data['nirs']['probe']['sourcePos2D'][:] )
print()
print( data['nirs']['probe']['sourcePos3D'][:] )
print()



 Alguns files no diretório... 


['26_run2.snirf', '14_run2.snirf', '19_run2.snirf', '31_run2.snirf', '3_run2.snirf']
Input snirf file: /content/drive/MyDrive/Cond 2/snirf/26_run2.snirf
Output snirf file: /content/snirf/26_run2.snirf


 26_run2.snirf sourcePos2D e sourcePos3D... 


[[17.   3. ]
 [12.   7.5]
 [ 6.   7.5]
 [ 1.5  3. ]
 [13.5  3. ]
 [ 4.5  3. ]]

[[17.   3.   0. ]
 [12.   7.5  0. ]
 [ 6.   7.5  0. ]
 [ 1.5  3.   0. ]
 [13.5  3.   0. ]
 [ 4.5  3.   0. ]]

Input snirf file: /content/drive/MyDrive/Cond 2/snirf/19_run2.snirf
Output snirf file: /content/snirf/19_run2.snirf


 19_run2.snirf sourcePos2D e sourcePos3D... 


[[17.   3. ]
 [12.   7.5]
 [ 6.   7.5]
 [ 1.5  3. ]
 [13.5  3. ]
 [ 4.5  3. ]]

[[17.   3.   0. ]
 [12.   7.5  0. ]
 [ 6.   7.5  0. ]
 [ 1.5  3.   0. ]
 [13.5  3.   0. ]
 [ 4.5  3.   0. ]]

